---
title: "Transplante de médula ósea"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo    = FALSE,   
  message = FALSE,   
  warning = FALSE,   
  error   = FALSE,   
  results = 'hide'   
)

library(dplyr)
library(here)
library(ggplot2)
library(forecast)
library(tseries)
library(TSA)
```




```{r Data}
data <- read.table(here("Proyecto4", "Ejercicio4", "tempNottingham.txt"), header = TRUE)
head(data)
```


```{r}
#Poniendo la grafica de nuestra serie de tiempo
ggtsdisplay(data)

```


```{r}
#Graficando el periodograma
periodogram(data,ylab='Variable x Periodogram')
# nuestro periodo es de 12 o 13, se debe de dividir el que se sale, entre 1 
```



Inciso b, defereciemos con lag 12


```{r}
resultado <- diff(data$x, lag =12)#Haciendo la serie estacionaria
ggtsdisplay(resultado)
```

```{r}
Box.test(resultado,type='Ljung-Box')
#H0: No hay autocorrelacion => es un ruido blanco 

```

Arma(p, q)

Consideramos un Arma(1,1)

ARMA(0,1)


# Ajusstando modelos Arma
```{r}
# ARMA (1,1) for the lagged differences

                              #p,d,q
res1=arima(resultado  ,order=c(1,0,1))
summary(res1)

```


```{r}
res2=arima(resultado  ,order=c(0,0,1))
summary(res2)


```




```{r}
fit_sarima <- Arima(
  data,
  order   = c(1, 0, 1),
  seasonal = list(order = c(1, 1, 1), period = 12)
)
summary(fit_sarima)
```

```{r}
checkresiduals(fit_sarima) 

```


```{r}
ggtsdisplay(residuals(fit_sarima))
Box.test(fit_sarima$x,type='Ljung-Box')
```



```{r}
# Predicción para los próximos 20 meses
pred_20 <- forecast(fit_sarima, h = 20)

# Ver los valores de predicción
pred_20

# Graficar la predicción con intervalos de confianza
autoplot(pred_20) +
  labs(title = "Predicción SARIMA para los próximos 20 meses",
       x = "Tiempo",
       y = "Temperatura") +
  theme_minimal()

```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```



